services:
  app:
    container_name: dev_serv
    build:
      dockerfile: Dockerfile
      context: ./server
    user: root
    working_dir: /home/node/app
    command: "yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./server:/home/node/app
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 5001:3000